products/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from .views import ProductDetailView, ProductListView, VariationListView

urlpatterns = [
    # Examples:
    # url(r'^(?P<id>\d+)$', 'products.views.product_detail_view_func', name='product_detail_function'),
    url(r'^$', ProductListView.as_view(), name='products'),
    url(r'^(?P<pk>\d+)$', ProductDetailView.as_view(), name='product_detail'),
    url(r'^(?P<pk>\d+)/inventory/$', VariationListView.as_view(), name='product_inventory'),
]

carts/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save, post_save

from products.models import Variation

class CartItem(models.Model):
    cart = models.ForeignKey("Cart")
    item = models.ForeignKey(Variation)
    quantity = models.PositiveIntegerField(default=1)
    line_item_total = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def __unicode__(self):
        return self.item.title

    def remove(self):
        return self.item.remove_from_cart()

def cart_item_pre_save_receiver(sender, instance, *args, **kwargs):
    print "lakshay ++++++++++++++++++++++++++++++++++++++++++++++++++"
    qty = instance.quantity

    print "qty +++++++++++++++++++++++++++++++++++++"
    print qty

    if qty >= 1:
        price = instance.item.get_price()
        line_item_total = Decimal(qty) * Decimal(price)
        print "line item total ++++++++++++++++++++++++++++"
        print line_item_total

        instance.line_item_total = line_item_total

pre_save.connect(cart_item_pre_save_receiver, sender=CartItem)

# def cart_item_pre_save_receiver(sender, instance, *args, **kwargs):
#     qty = instance.quantity
#     if qty:
#         price = instance.item.get_price()
#         line_item_total = Decimal(qty)* Decimal(price)
#         instance.line_item_total = line_item_total

# pre_save.connect(cart_item_pre_save_receiver, sender=CartItem)

def cart_item_post_save_receiver(sender, instance, *args, **kwargs):
    instance.cart.update_subtotal()

post_save.connect(cart_item_post_save_receiver, sender=CartItem)


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    items = models.ManyToManyField(Variation, through=CartItem)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    subtotal = models.DecimalField(max_digits=50, decimal_places=2, null=True, blank=True)

    def __unicode__(self):
        return str(self.id)

    def update_subtotal(self):
        subtotal = 0
        items = self.cartitem_set.all()
        for item in items:
            subtotal += item.line_item_total
        self.subtotal = subtotal
        self.save()

carts/views.py
from django.core.urlresolvers import reverse
from django.views.generic.base import View
from django.views.generic.detail import SingleObjectMixin

from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import render, get_object_or_404

from products.models import Variation
from carts.models import Cart, CartItem

class CartView(SingleObjectMixin, View):
    model = Cart
    template_name = "carts/view.html"

    def get_object(self, *args, **kwargs):
        self.request.session.set_expiry(0)
        cart_id = self.request.session.get("cart_id")

        if cart_id == None:
            cart = Cart()
            cart.save()
            cart_id = cart.id
            self.request.session["cart_id"] = cart_id

        cart = Cart.objects.get(id=cart_id)
        if self.request.user.is_authenticated():
            cart.user = self.request.user
            cart.save()
        return cart


    def get(self, request, *args, **kwargs):
        cart = self.get_object()
        item_id = request.GET.get("item")
        delete_item = request.GET.get("delete",False)
        item_added = False
        if item_id:
            item_instance = get_object_or_404(Variation, id=item_id)
            qty = request.GET.get("qty", 1)
            try:
                if int(qty) < 1 :
                    delete_item = True
            except:
                raise Http404

            cart_item, created = CartItem.objects.get_or_create(cart=cart, item=item_instance)
            item_added = False
            if created:
                item_added = True
            if delete_item:
                cart_item.delete()
            else:
                cart_item.quantity = qty
                cart_item.save()
            if not request.is_ajax():
                return HttpResponseRedirect(reverse("cart"))

        if request.is_ajax():
            try:
                total = cart_item.line_item_total
            except:
                total = None
            try:
                subtotal = cart_item.cart.subtotal
            except:
                subtotal = None

            data = {
                "deleted":delete_item,
                "item_added":item_added,
                "line_total":total,
                "subtotal":subtotal
            }
            return JsonResponse(data)
            # print request.GET.get("item")
            # return JsonResponse({"deleted":delete_item, "item_added":item_added })

        context = {
            "object":self.get_object()
        }
        template = self.template_name
        return render(request, template, context)

    # def get_object(self, *args, **kwargs):
    #     self.request.session.set_expiry(0) #session ends as the browser closed
    #     cart_id = self.request.session.get("cart_id")
    #     if cart_id == None:
    #         cart = Cart()
    #         cart.save()
    #         cart_id = cart.id
    #         self.request.session["cart_id"] = cart_id
    #     cart = Cart.objects.get(id=cart_id)
    #     if self.request.user.is_authenticated():
    #         cart.user = self.request.user
    #         cart.save()
    #     return cart

    # def get(self, request, *args, **kwargs):
    #     cart = self.get_object()
    #     item_id = request.GET.get("item")
    #     delete_item = request.GET.get("delete")
    #     if item_id:
    #         item_instance = get_object_or_404(Variation, id=item_id)
    #         qty = request.GET.get("qty", 1)
    #         try:
    #             if int(qty) < 1:
    #                 delete_item = True
    #         except:
    #             raise Http404

    #         cart_item = CartItem.objects.get_or_create(cart=cart, item=item_instance)[0]
    #         if delete_item:
    #             cart_item.delete()
    #             cart_item.save()
    #         else:
    #             cart_item.quantity = qty
    #             cart_item.save()

    #     context = {
    #         "object": self.get_object()
    #     }

    #     template = self.template_name
    #     return render(request, template, context)

carts/templates/carts/view.html
{% extends "base.html" %}

<script>
{% block jquery %}

$(".item-qty").change(function(){
    // $(this).next(".btn-update").fadeIn();
        // event.preventDefault();
        var item = $(this).prev("input[type='hidden']").val();
        // var item = $("#add-form").serialize();
        var qty = $(this).val();
        var data = {
            item:item,
            qty:qty
        }
        $.ajax({
            type:"GET",
            url:"{% url 'cart' %}",
            data: data,
            success: function(data){
                $("#jquery-message").text("Added" + data.item_added + " Deleted " + data.deleted)
                if(data.deleted){
                    $("#item-"+item).fadeout();
                }else{
                    $("#item-line-total-"+item).text(data.line_total);
                    $("#id_subtotal").text(data.subtotal);

                }
            },
            error:function(response, error){
                $('#add-form').submit();
            }
        })


})

{% endblock %}

</script>

{{ object }}

{% block content %}

    <table class="table">
    {% for item in object.cartitem_set.all %}

    <tr id="item-{{item.item.id}}">
    	<td>
	    	  {{ item.item.get_title }}
	    </td>
	     <td>
            <form action="." method="GET">
                <input type="hidden" name="item" value="{{ item.item.id }}"/>
                <input type="number" class="item-qty" name="qty" value="{{ item.quantity }}"/>
                <input type="submit" class="btn-update btn btn-link" value="Update item" style="display:none;"/>
            </form>
        </td>
        <td>
            {{ item.item.price }}
        </td>
	      <td id="item-line-total-{{ item.item.id }}">
	    	    {{ item.line_item_total }}
	      </td>
	      <td class="text-right">
            <a href="{{ item.remove }}">X</a>
        </td>
	 </tr>
    {% endfor %}
    <tr>
        <td colspan='4' class="text-right" id="id_subtotal">subtotal: {{ object.subtotal }} </td>
    </tr>
    </table>
{% endblock %}